In [10]:
#importing some useful packages
import pickle
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from matplotlib.colors import hsv_to_rgb
import numpy as np
import math
from PIL import Image
import cv2
import os, glob
from sklearn.linear_model import LinearRegression

In [11]:
def cal_undistort(img, objpoints, imgpoints):
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, img.shape[1::-1], None, None)
    undist = cv2.undistort(img, mtx, dist, None, mtx)
    return undist,mtx,dist

In [12]:
warped=0
def corners_unwarp(img, nx, ny, mtx, dist):
    # Pass in your image into this function
    # Write code to do the following steps
    # 1) Undistort using mtx and dist
    #undist = cv2.undistort(img, mtx, dist, None, mtx)
    # 2) Convert to grayscale
    #grayscale = cv2.cvtColor(np.array(undist),cv2.COLOR_RGB2GRAY)
    img_size = img.shape[1::-1]
    # 3) Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(img,(nx,ny), None)
    # 4) If corners found: 
    if ret == True:
            # a) draw corners
            # b) define 4 source points src = np.float32([[,],[,],[,],[,]])
        src = np.float32([[435,109],[1104,225],[1076,635],[463,772]])
                 #Note: you could pick any four of the detected corners 
                 # as long as those four corners define a rectangle
                 #One especially smart way to do this would be to use four well-chosen
                 # corners that were automatically detected during the undistortion steps
                 #We recommend using the automatic detection of corners in your code
            # c) define 4 destination points dst = np.float32([[,],[,],[,],[,]])
        dst = np.float32([[430,110],[900,110],[900,700],[430,700]])
            # d) use cv2.getPerspectiveTransform() to get M, the transform matrix
        M = cv2.getPerspectiveTransform(src, dst)
            # e) use cv2.warpPerspective() to warp your image to a top-down view
        warped = cv2.warpPerspective(img, M, img_size, flags=cv2.INTER_LINEAR)
    #delete the next two lines
     
    return warped, M


In [13]:
%matplotlib qt

all_images = glob.glob('test_images_camera_distortion/GOPR0032.jpg')

# Arrays to store object points and image points from all images
objpoints = []
imgpoints = []

x = 8
y = 6
objp = np.zeros((x*y,3),np.float32)
objp[:,:2] = np.mgrid[0:x,0:y].T.reshape(-1,2) #x,y coordinates

for file_name in all_images:
    
    image = mpimg.imread(file_name)
    #plt.imshow(np.array(image))
    grayscale = cv2.cvtColor(np.array(image),cv2.COLOR_BGR2GRAY)

    ret, corners = cv2.findChessboardCorners(grayscale,(x,y), None)

    if ret == True:
        imgpoints.append(corners)
        objpoints.append(objp)
    
        image = cv2.drawChessboardCorners(image,(x,y),corners, ret)
    
    undistorted,mtx,dist = cal_undistort(image, objpoints, imgpoints)
    

    f, (ax1, ax2) = plt.subplots(1, 2, figsize=(24, 9))
    f.tight_layout()
    ax1.imshow(image)
    ax1.set_title('Original Image', fontsize=50)
    ax2.imshow(undistorted)
    ax2.set_title('Undistorted Image', fontsize=50)
    plt.subplots_adjust(left=0., right=1, top=0.9, bottom=0.)
#"""


In [25]:
#print(corners[0])
print(corners[8-1])
#print(corners[-1])
#print(corners[-8])
print('corners')
print(corners)

[[1030.1838  270.0841]]
corners
[[[ 462.5541   161.35435]]

 [[ 579.8831   169.6921 ]]

 [[ 687.8876   184.07697]]

 [[ 782.25793  201.73709]]

 [[ 862.12164  220.1853 ]]

 [[ 928.7005   238.08647]]

 [[ 984.37244  254.6542 ]]

 [[1030.1838   270.0841 ]]

 [[ 456.5541   274.14923]]

 [[ 578.6139   278.18323]]

 [[ 690.1587   287.34586]]

 [[ 786.5488   298.59094]]

 [[ 867.05115  310.93097]]

 [[ 934.02606  322.46457]]

 [[ 989.1491   333.13928]]

 [[1035.0569   343.04868]]

 [[ 454.80762  397.9013 ]]

 [[ 578.5601   396.98193]]

 [[ 691.4437   399.01077]]

 [[ 788.14325  402.43298]]

 [[ 869.05475  406.35153]]

 [[ 935.97534  410.4593 ]]

 [[ 991.04346  414.30936]]

 [[1036.211    418.09845]]

 [[ 458.96588  524.49445]]

 [[ 580.934    518.83203]]

 [[ 692.2226   512.9375 ]]

 [[ 788.0009   507.76083]]

 [[ 868.18976  503.25314]]

 [[ 934.6849   499.28427]]

 [[ 989.3737   496.14224]]

 [[1034.5117   493.452  ]]

 [[ 467.2636   643.98975]]

 [[ 584.6483   634.0442 ]]

 [[ 692.01154  6

In [ ]:
  
    img_size = undistorted.shape[1::-1]
    # 3) Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(undistorted,(x,y), None)
    # 4) If corners found: 
    if ret == True:
            # a) draw corners
            # b) define 4 source points src = np.float32([[,],[,],[,],[,]])
        src = np.float32([[435,109],[1104,225],[1076,635],[463,772]])
                 #Note: you could pick any four of the detected corners 
                 # as long as those four corners define a rectangle
                 #One especially smart way to do this would be to use four well-chosen
                 # corners that were automatically detected during the undistortion steps
                 #We recommend using the automatic detection of corners in your code
            # c) define 4 destination points dst = np.float32([[,],[,],[,],[,]])
        dst = np.float32([[430,110],[900,110],[900,700],[430,700]])
            # d) use cv2.getPerspectiveTransform() to get M, the transform matrix
        M = cv2.getPerspectiveTransform(src, dst)
            # e) use cv2.warpPerspective() to warp your image to a top-down view
        warped = cv2.warpPerspective(undistorted, M, img_size, flags=cv2.INTER_LINEAR)
        
    top_down = warped    
        
    #top_down,perspective_M = corners_unwarp(undistorted, x, y, mtx, dist)
    
    f, (ax1, ax2) = plt.subplots(1, 2, figsize=(24, 9))
    f.tight_layout()
    ax1.imshow(image)
    ax1.set_title('Original Image', fontsize=50)
    ax2.imshow(warped,cmap='gray')
    ax2.set_title('Undistorted and Warped Image', fontsize=50)
    plt.subplots_adjust(left=0., right=1, top=0.9, bottom=0.)
  